version: "3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "postgres"
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
volumes:
  db: